version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
    - 8000:8000
    - 8433:8433
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./upload:/var/www/upload
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
    depends_on:
    - app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    container_name: certboot
    volumes:
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  app:
    container_name: app
    restart: always
    build: .
    volumes:
    - ./logs:/app/logs
    - ./upload:/app/upload
    expose:
    - "8080"
    ports:
    - "5005:5005"
    environment:
    - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
    - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
    - FACEBOOK_APP_TOKEN=${FACEBOOK_APP_TOKEN}
    - JWT_SECRET=${JWT_SECRET}
    - VK_APP_ID=${VK_APP_ID}
    - VK_APP_TOKEN=${VK_APP_TOKEN}
    - VK_APP_SECRET=${VK_APP_SECRET}
    - DB_DRIVER_CLASS_NAME=${DB_DRIVER_CLASS_NAME}
    - DB_URL=${DB_URL}
    - DB_USER_NAME=${DB_USER_NAME}
    - DB_PASSWORD=${DB_PASSWORD}
    - UPLOAD_DIR=${UPLOAD_DIR}
    - UPLOAD_CATEGORY_DIR=${UPLOAD_CATEGORY_DIR}
    - MAIL_HOST=${MAIL_HOST}
    - MAIL_PORT=${MAIL_PORT}
    - MAIL_USERNAME=${MAIL_USERNAME}
    - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
    - db
  db:
    container_name: db
    image: postgres:10
    restart: always
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=${DB_USER_NAME}
    - POSTGRES_USER=${DB_PASSWORD}
    - POSTGRES_DB=${DB_NAME}
