server:
  port: ${PORT}
spring:
    profiles:
      active: prod
    datasource:
      driver-class-name: ${DB_DRIVER_CLASS_NAME}
      url: ${DB_URL}
      userName: ${DB_USER_NAME}
      password: ${DB_PASSWORD}
app:
  social:
    facebook:
      appId: ${FACEBOOK_APP_ID}
      appSecret: ${FACEBOOK_APP_SECRET}
      appToken: ${FACEBOOK_APP_TOKEN}
    vk:
      appId: ${VK_APP_ID}
      appSecret: ${VK_APP_SECRET}
      appToken: ${VK_APP_TOKEN}
  jwt:
    secret: ${JWT_SECRET}
  upload:
    dir: ${UPLOAD_DIR}
