server:
  port: ${PORT}
spring:
    profiles:
      active: prod
    datasource:
      driver-class-name: ${DB_DRIVER_CLASS_NAME}
      url: ${DB_URL}
      userName: ${DB_USER_NAME}
      password: ${DB_PASSWORD}
app:
  firebase:
    database:
      url: ${FIREBASE_DATABASE_URL}
    config:
      path: bibliographya-65e17-firebase-adminsdk-tyixc-a47f9151b6.json
  pusher:
    appId: ${PUSHER_APP_ID}
    key: ${PUSHER_KEY}
    secret: ${PUSHER_SECRET}
    cluster: ${PUSHER_CLUSTER}
  social:
    facebook:
      appId: ${FACEBOOK_APP_ID}
      appSecret: ${FACEBOOK_APP_SECRET}
      appToken: ${FACEBOOK_APP_TOKEN}
    vk:
      appId: ${VK_APP_ID}
      appSecret: ${VK_APP_SECRET}
      appToken: ${VK_APP_TOKEN}
  jwt:
    secret: ${JWT_SECRET}
  upload:
    dir: ${UPLOAD_DIR}
