server:
  port: 8000
spring:
    social:
      facebook:
        appId: ${FACEBOOK_APP_ID}
        appSecret: ${FACEBOOK_APP_SECRET}
        appToken: ${FACEBOOK_APP_TOKEN}
      vk:
        appId: ${VK_APP_ID}
        appSecret: ${VK_APP_SECRET}
        appToken: ${VK_APP_TOKEN}
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/bibliography
      userName: postgres
      password: postgres
app:
  jwt:
    secret: ${JWT_SECRET}
  upload:
    dir: upload