spring:
    datasource:
      driver-class-name: ${DB_DRIVER_CLASS_NAME}
      url: ${DB_URL}
      userName: ${DB_USER_NAME}
      password: ${DB_PASSWORD}
    profiles:
      active: ^spring.profiles.active^
    mail:
      host: ${MAIL_HOST}
      port: ${MAIL_PORT}
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
      protocol: smtp
      properties:
        mail:
          transport:
            protocol: smtp
          smtp:
            auth: true
            starttls:
              enable: true
          timeout: 8000
app:
  social:
    facebook:
      appId: ${FACEBOOK_APP_ID}
      appSecret: ${FACEBOOK_APP_SECRET}
      appToken: ${FACEBOOK_APP_TOKEN}
    vk:
      appId: ${VK_APP_ID}
      appSecret: ${VK_APP_SECRET}
      appToken: ${VK_APP_TOKEN}
  jwt:
    secret: ${JWT_SECRET}
  upload:
    root: ${UPLOAD_DIR}
    category-root: ${UPLOAD_CATEGORY_DIR}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
logging:
  file: logs/bibliographya.log
ui:
  name: localhost