ALTER TABLE "user" ADD COLUMN IF NOT EXISTS phone VARCHAR(255) UNIQUE;
ALTER TABLE "user" ALTER COLUMN email DROP NOT NULL;
ALTER TABLE "user" DROP CONSTRAINT IF EXISTS user_email_key;
ALTER TABLE "user" ADD CONSTRAINT user_email_key UNIQUE(email);
ALTER TABLE "user" DROP COLUMN IF EXISTS email_verified;
ALTER TABLE "user" DROP COLUMN IF EXISTS phone_verified;