CREATE TABLE IF NOT EXISTS country(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

ALTER TABLE biography ADD COLUMN IF NOT EXISTS country_id INT REFERENCES country(id) ON DELETE SET NULL;

INSERT INTO country (name) VALUES ('Россия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Алжир') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Американский Самоа') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Андорра') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Ангола') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Ангилья') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Антарктика') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Антигуа и Барбуда') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Аргентина') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Армения') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Аруба') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('на море') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Австралия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Австрия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Азербайджан') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Багамские острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Бахрейн') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Бангладеш') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Барбадос') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Беларусь') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Бельгия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Белиз') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Бенин') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Бермуды') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Бутан') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Боливия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Босния и Герцеговина') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Ботсвана') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('остров Буве') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Бразилия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Британские территории Индийского океана') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Бруней') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Болгария') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Буркина Фасо') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Бурунди') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Камбоджа') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Камерун') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Канада') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('острова Зеленого Мыса') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Каймановы острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Центральная Африканская Республика') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Чад') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Нормандские острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Чили') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Китайская Народная Республика') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('остров Рождества') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Кокосовые острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Колумбия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Коморские острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Конго') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Демократическая республика Конго') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('острова Кука') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Коста Рика') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Кот-д''Ивуар') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Хорватия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Куба') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Кипр') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Чехия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Дания') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Джибути') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Доминика') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Доминиканская республика') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Эквадор') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Египет') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сальвадор') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Англия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Экваториальная Гвинея') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Эритрея') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Эстония') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Эфиопия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('ЕС') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Фарерские острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Фолклендские (Мальвинские) острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Фиджи') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Финляндия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Франция') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Французская Гвиана') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Французская Полинезия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Французские Южные Территории') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Габон') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гамбия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Грузия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Германия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гана') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гибралтар') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Греция') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гренландия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гренада') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гваделупа') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гуам') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гватемала') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гвинея') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гвинея-Бисау') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гайана') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гаити') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('острова Герда и МакДональда') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гондурас') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Гонконг (Китай)') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Венгрия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Исландия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('в полете') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Индия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Индонезия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Иран') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Ирак') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Ирландия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('остров Мэн') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Израиль') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Италия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Ямайка') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Япония') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Иордания') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Казахстан') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Кения') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Кирибати') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Корея') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Корейская Народная Демократическая республика') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Кувейт') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Кыргызстан') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Лаос') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Латвия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Ливан') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Лесото') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Либерия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Ливия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Лихтенштейн') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Литва') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Люксембург') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Макао (Китай)') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Македония') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Мадагаскар') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Малави') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Малайзия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Мальдивские острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Мали') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Мальта') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Маршалловы острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Мартиника') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Мавритания') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Маврикий') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Майотта') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Мексика') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Микронезия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Молдова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Монако') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Монголия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Монтсеррат') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Марокко') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Мозамбик') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Мьянма') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Намибия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Науру') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Непал') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Нидерланды') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Антильские острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Новая Каледония') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Новая Зеландия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Никарагуа') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Нигер') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Нигерия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Ниуэ') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('остров Норфолк') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Марианские острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Норвегия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Северная Ирландия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Оман') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Пакистан') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Палау') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Палестина') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Панама') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Папуа - Новая Гвинея') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Парагвай') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Перу') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Филиппины') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('остров Питкэрн') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Польша') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Португалия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Пуэрто-Рико') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Катар') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Реюньон') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Румыния') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Руанда') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('остров Святой Елены') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сент-Китс и Невис') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сент-Люсия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сен-Пьер и Микелон') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сент-Винсент и Гренадины') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('острова Самоа') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сан-Марино') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сан-Томе и Принсипи') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Саудовская Аравия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Шотландия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сенегал') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сейшельские острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сьерра-Леоне') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сингапур') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Словакия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Словения') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Соломоновы острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сомали') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('ЮАР') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Южная Георгия и Южные Сандвичевы острова') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('в космосе') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Испания') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Шри Ланка') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Судан') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Суринам') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('острова Свалбард и Ян Майен') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Свазиленд') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Швеция') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Швейцария') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Сирия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Тайвань (Республика Китай)') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Таджикистан') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Танзания') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Тайланд') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Восточный Тимор') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Того') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Токелау') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Тонга') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Тринидад и Тобаго') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Тунис') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Турция') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Туркменистан') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('острова Туркс и Кайкос') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Тувалу') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Уганда') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Украина') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('ООН') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Арабские Эмираты') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Великобритания') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Соединенные Штаты Америки') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Отдаленные Острова США') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Уругвай') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Узбекистан') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Вануату') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Ватикан') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Венесуэла') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Вьетнам') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Виргинские острова (Британские)') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Виргинские острова (США)') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Уэльс') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('острова Валлис и Футуна') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Западная Сахара') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Йемен') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Югославия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Замбия') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Зимбабве') ON CONFLICT(name) DO NOTHING;
INSERT INTO country (name) VALUES ('Афганистан') ON CONFLICT(name) DO NOTHING;