version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
    - 8000:8000
    volumes:
    - ./nginx/conf.d/dev:/etc/nginx/conf.d
    - ./upload:/var/www/upload
    depends_on:
    - app
  app:
    container_name: app
    restart: always
    build: ../../../
    volumes:
    - ./logs:/app/logs
    - ./upload:/app/upload
    expose:
    - "8080"
    ports:
    - "5005:5005"
    env_file:
    - app.env
    depends_on:
    - db
  db:
    container_name: db
    image: postgres:10
    restart: always
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    env_file:
    - db.env