version: '3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    volumes:
    - ./grafana:/var/lib/grafana
    ports:
    - "3000:3000"
    links:
    - prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./prometheus:/prometheus
    ports:
    - "9090:9090"
