CREATE TABLE IF NOT EXISTS role (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO role("email") VALUES('ROLE_ADMIN');

INSERT INTO role("email") VALUES('ROLE_MODERATOR');

INSERT INTO role("email") VALUES('ROLE_USER');

INSERT INTO role("email") VALUES('ROLE_SOCIAL_USER');

INSERT INTO role("email") VALUES('ROLE_DEVELOPER');