CREATE TABLE IF NOT EXISTS role (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO role("name") VALUES('ROLE_ADMIN');

INSERT INTO role("name") VALUES('ROLE_MODERATOR');

INSERT INTO role("name") VALUES('ROLE_USER');

INSERT INTO role("name") VALUES('ROLE_SOCIAL_USER');

INSERT INTO role("name") VALUES('ROLE_DEVELOPER');